import { db } from "~/lib/db";

async function main() {
    const players = [
      { name: 'Gannon Buhr' },
      { name: 'Ezra Robinson' },
      { name: 'Richard Wysocki' },
      { name: 'Gavin Rathbun' },
      { name: 'Calvin Heimburg' },
      { name: 'Kyle Klein' },
      { name: 'Niklas Anttila' },
      { name: 'Gavin Babcock' },
      { name: 'Luke Taylor' },
      { name: 'Casey White' },
      { name: 'Luke Humphries' },
      { name: 'Chandler Fry' },
      { name: 'Eagle McMahon' },
      { name: 'Zachary Nash' },
      { name: 'Bradley Williams' },
      { name: 'AJ Carey' },
      { name: 'Paul Ulibarri' },
      { name: 'Tuomas Hyytiäinen' },
      { name: 'Linus Carlsson' },
      { name: 'Connor Rock' },
      { name: 'Isaac Robinson' },
      { name: 'Corey Ellis' },
      { name: 'Eric Oakley' },
      { name: 'Emerson Keith' },
      { name: 'Garrett Gurthie' },
      { name: 'Micah Groth' },
      { name: 'Randon Latta' },
      { name: 'James Conrad' },
      { name: 'Nikko Locastro' },
      { name: 'James Proctor' },
      { name: 'Joseph Anderson' },
      { name: 'Joe Notch' },
      { name: 'Matt Bell' },
      { name: 'Jaden Rye' },
      { name: 'Cole Redalen' },
      { name: 'Kevin Jones' },
      { name: 'Parker Welck' },
      { name: 'Joona Heinänen' },
      { name: 'Adam Hammes' },
      { name: 'Aaron Gossage' },
      { name: 'Ezra Aderhold' },
      { name: 'Austin Turner' },
      { name: 'Chandler Kramer' },
      { name: 'Paul McBeth' },
      { name: 'Ty Love' },
      { name: 'Justin Rosak' },
      { name: 'Jake Hebenheimer' },
      { name: 'Andrew Marwede' },
      { name: 'Andrew Fish' },
      { name: 'Colten Montgomery' },
      { name: 'Albert Tamm' },
      { name: 'Lucas Oberholtzer Hess' },
      { name: 'Chris Clemons' },
      { name: 'Raven Newsom' },
      { name: 'Jake Brown' },
      { name: 'Max Regitnig' },
      { name: 'Mason Ford' },
      { name: 'Zach Arlinghaus' },
      { name: 'Evan Scott' },
      { name: 'Jeremy Koling' },
      { name: 'Joey Temali' },
      { name: 'Kevin Kiefer III' },
      { name: 'Jared Stoll' },
      { name: 'Anthony Barela' },
      { name: 'Nathan Sexton' },
      { name: 'Nate Hecker' },
      { name: 'Connor O\'Reilly' },
      { name: 'Calvin Lonnquist' },
      { name: 'Sullivan Tipton' },
      { name: 'Jake Monn' },
      { name: 'Jacob Courtis' },
      { name: 'Carter Ahrens' },
      { name: 'Luke Samson' },
      { name: 'Nathan Doss' },
      { name: 'Dustin Keegan' },
      { name: 'Scott Withers' },
      { name: 'Andrew Presnell' },
      { name: 'Jesse Nieminen' },
      { name: 'Maximus Meyer' },
      { name: 'Justin Anderson' },
      { name: 'Robert Burridge' },
      { name: 'Kirby Snyder' },
      { name: 'Randy Dueck' },
      { name: 'Kieran Hampson' },
      { name: 'Noah Fiveash' },
      { name: 'Thomas Gilbert' },
      { name: 'Anthony Bodanza' },
      { name: 'Colin Bryant' },
      { name: 'Braeden Sides' },
      { name: 'Jason Lawson' },
      { name: 'Alden Harris' },
      { name: 'Ryan Chesla' },
      { name: 'Trevon Crowe' },
      { name: 'Broden Barlow' },
      { name: 'Jake Wolff' },
      { name: 'Väinö Mäkelä' },
      { name: 'James Leon' },
      { name: 'Dallas Garber' },
      { name: 'Christopher Robbins' },
      { name: 'Jace Foster' },
      { name: 'Daniel Pfaff' },
      { name: 'Sean Martin' },
      { name: 'Nicholas Duran' },
      { name: 'Samuel Snider' },
      { name: 'Adam Alexander' },
      { name: 'Tony "Candy Arms" Cahill' },
      { name: 'Huntington Coats' },
      { name: 'D.J. Herrington' },
      { name: 'Brady Och' },
      { name: 'Kurtis Kloke' },
      { name: 'Taylor Coulam' },
      { name: 'Drew Gibson' },
    ];
  
    for (const player of players) {
      await db.player.create({
        data: player,
      });
    }
  }
  
  main()
    .catch((e) => {
      console.error(e);
      process.exit(1);
    })
    .finally(async () => {
      await db.$disconnect();
    });